# site settings
title: Banan Aljarrah
subtitle: Clinical Pharmacist & Data Analyst
email: banan.yourname@gmail.com
description: >
  A responsive academic portfolio showcasing projects in medical data science, 
  survival analysis, and clinical research.  
  Built with love using R and GitHub Pages.

baseurl: ""  # Leave empty if this is your main GitHub Pages repo
url: "https://bananbashar.github.io"

author: Dr. Banan Aljarrah
street_address: Amman, Jordan
city: Amman
state: 
zip_code: 
country: Jordan
phone: 

# homepage tiles
tiles-source: pages  # or "posts" if you want to show blog posts
tiles-count: 6

# social settings
socials:
  GitHub: https://github.com/Bananbashar
  LinkedIn: https://www.linkedin.com/in/banan-aljarrah
  Twitter: 
  Instagram: 
  Facebook: 

# build sett
